import os
import json
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from hashprice_engine import calculate

BRAND = os.getenv("BRAND","beardminer")

with open(f"brands/{BRAND}.json") as f:
    BRAND_CONFIG=json.load(f)

ASCII_HEADER=BRAND_CONFIG["ascii"]
BRAND_NAME=BRAND_CONFIG["name"]

app = FastAPI()

THEMES = {
    "orange": {"accent":"#ff9900","bg":"#0b0b0b"},
    "green": {"accent":"#00ff88","bg":"#0b0b0b"},
    "blue": {"accent":"#4da6ff","bg":"#0b0b0b"},
    "white": {"accent":"#111111","bg":"#ffffff"}
}

def build_trend(data,width):

    trend=data["trend"]
    max_val=max(float(v) for v in trend["hashprice_1d"]) or 1

    lines=[]

    for _,row in trend.iterrows():

        date=row["time"].strftime("%Y-%m-%d")
        val=float(row["hashprice_1d"])

        bar_len=max(1,int((val/max_val)*width))
        bar="▓"*bar_len

        lines.append(f"{date} | {bar:<{width}} ${val:,.2f}")

    marker="▲" if data["pct_vs_7d"]>=0 else "▼"

    lines.append("─"*(width+26))
    lines.append(
        f"{data['timestamp'][:10]} | {'▓'*min(width,24):<{width}} "
        f"${data['hashprice_rt']:,.2f} {marker} {data['pct_vs_7d']:+.2f}% vs 7D"
    )

    return "\n".join(lines)

@app.get("/",response_class=HTMLResponse)
def dashboard(request:Request):

    theme_name=request.query_params.get("theme","green")
    theme=THEMES.get(theme_name,THEMES["green"])

    data=calculate()

    trend_desktop=build_trend(data,56)
    trend_mobile=build_trend(data,24)

    HASHPRICE_RT=data["hashprice_rt"]

    html=f"""
<html>
<head>

<meta http-equiv="refresh" content="60">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<style>

body {{
background:{theme["bg"]};
color:{theme["accent"]};
font-family:Menlo,Monaco,Consolas,monospace;
max-width:1200px;
margin:30px auto;
padding:20px;
line-height:1.4;
}}

.box {{
border:1px solid {theme["accent"]};
padding:22px;
margin-bottom:22px;
}}

.theme-btn {{
margin-right:10px;
text-decoration:none;
color:{theme["accent"]};
border:1px solid {theme["accent"]};
padding:4px 10px;
font-size:12px;
}}

.ascii-logo {{
white-space:pre;
font-size:14px;
}}

.mobile-logo {{
display:none;
font-size:34px;
font-weight:bold;
letter-spacing:2px;
}}

.main-title {{
font-size:38px;
font-weight:bold;
}}

.kpi {{
font-size:64px;
font-weight:bold;
}}

.subtle {{
font-size:22px;
opacity:.85;
}}

pre.trend {{
white-space:pre;
margin:0;
font-size:15px;
}}

.trend-mobile {{
display:none;
}}

@media (max-width:700px) {{

.ascii-logo {{display:none;}}

.mobile-logo {{display:block;}}

.kpi {{font-size:42px;}}

.main-title {{font-size:26px;}}

.trend-desktop {{display:none;}}

.trend-mobile {{display:block;}}

}}

</style>
</head>

<body>

<div>
<a href="/?theme=orange" class="theme-btn">Orange</a>
<a href="/?theme=green" class="theme-btn">Green</a>
<a href="/?theme=blue" class="theme-btn">Blue</a>
<a href="/?theme=white" class="theme-btn">White</a>
</div>

<div class="box">

<pre class="ascii-logo">
{ASCII_HEADER}
</pre>

<div class="mobile-logo">{BRAND_NAME}</div>

<div class="main-title">BITCOIN HASHPRICE DASHBOARD</div>

Last Updated: {data["timestamp"]}

</div>

<div class="box">
<strong>BTC Spot Price</strong><br><br>
<div class="kpi">${data["spot"]:,.2f}</div>
</div>

<div class="box">
<strong>Realtime Hashprice (USD / PH / Day)</strong><br><br>
<div class="kpi">${data["hashprice_rt"]:,.2f}</div>
<div class="subtle">
{"▲" if data["pct_vs_7d"]>=0 else "▼"} {data["pct_vs_7d"]:+.2f}% vs 7D
</div>
</div>

<div class="box">

<strong>Network State</strong><br><br>

Network Hashrate: {data["network_hashrate_ph"]:,.0f} PH/s<br>
Block Reward: {data["block_reward"]:.3f} BTC<br>
Fees (BTC/day): {data["fee_btc"]:.3f}<br>
Fee % (est): {data["fee_pct"]:.2f}%

</div>

<div class="box">
1-Day Raw: ${data["hashprice_1d"]:.2f}<br>
7-Day Smoothed: ${data["hashprice_7d"]:.2f}
</div>

<div class="box">

<strong>Recent Trend</strong><br><br>

<pre class="trend trend-desktop">{trend_desktop}</pre>
<pre class="trend trend-mobile">{trend_mobile}</pre>

</div>

<div class="box">

<details>

<summary><strong>Profitability Calculator</strong></summary>

<br>

Total PH<br>
<input id="ph" value="100"><br><br>

Machine Efficiency (J/TH)<br>
<input id="eff" value="18"><br><br>

Power Price ($/kWh)<br>
<input id="power" value="0.05"><br><br>

<button onclick="calc()">Calculate</button>

<div id="result" style="margin-top:15px;"></div>

</details>

</div>

<div class="box">

<details>

<summary><strong>How This Dashboard Calculates Hashprice</strong></summary>

<br>

Realtime Hashprice = estimated revenue generated by 1 PH/s of Bitcoin mining power.

<br><br>

Formula:

<br><br>

(Block Reward + Fees) × BTC Price ÷ Network Hashrate

<br><br>

7-Day hashprice smooths revenue and hashrate to show the structural mining economy.

</details>

</div>

<script>

function calc() {{

let ph=parseFloat(document.getElementById("ph").value)
let eff=parseFloat(document.getElementById("eff").value)
let power=parseFloat(document.getElementById("power").value)

let revenue=ph*{HASHPRICE_RT}
let power_kw=ph*eff
let power_cost=power_kw*24*power
let profit=revenue-power_cost

document.getElementById("result").innerHTML=
"Daily Revenue: $"+revenue.toFixed(2)+"<br>"+
"Daily Power Cost: $"+power_cost.toFixed(2)+"<br>"+
"Daily Profit: $"+profit.toFixed(2)

}}

</script>

</body>
</html>
"""

    return HTMLResponse(content=html)
